version: "3.2"
services:
  template-serverless-service-python-employee:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    entrypoint: ["sh", "./docker/python/entrypoint.sh"]
    privileged: true
    stdin_open: true  # <-- Habilita entrada interativa
    tty: true         # <-- Mantém o terminal ativo
    environment:
      AWS_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE
      AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      TEST_ENV: ${TEST_ENV}
      DB_HOST: "mysql"
      DB_PORT: 3306
      DB: store
      DB_USER: root
      DB_PASSWORD: store
      TURNSTILE_API_URL: "http://turnstileapi:5000"
    depends_on:
      - "localstack"
      - "redis"
    ports:
      - 5100:5100
    networks:
      - service-python-v1
    volumes:
      - ./:/app
  redis:
    image: "redis:alpine"
    ports:
      - 6370:6370
    expose:
      - 6370
    networks:
      - service-python-v1
  localstack:
    image: localstack/localstack
    privileged: true
    ports:
      - "4583:4583"
      - "4584-4599:4584-4599"
      - "9079:9079"
      - "8089:8089"
    environment:
      SERVICES: sqs,lambda,cloudwatch,s3
      DOCKER_HOST: unix:///var/run/docker.sock
      PORT_WEB_UI: 9070
      LAMBDA_EXECUTOR: local
      DEBUG: 1
      HOSTNAME_EXTERNAL: localstack
    networks:
      - service-python-v1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/localstack-data:/var/lib/localstack
  turnstileapi:
    container_name: turnstileapi
    build:
      context: ../Turnstile.API
      dockerfile: Dockerfile
    networks:
      - service-python-v1
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
networks:
  service-python-v1:
    external: true
